src/app/urls.py
import imp
from django.urls import path
from django.contrib.auth import views as auth_views

from app.views.index import index
from app.views.auth import register
from app.views.mytime import mytime


app_name = 'app'


urlpatterns = [
    path('', index, name='index'),
    path('mytime/', mytime, name='mytime'),
    path('auth/login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(next_page='app:index'), name='logout'),
    path('auth/register/', register, name='register'),
]

src/core/urls.py
"""
Main urls
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

src/app/models/mytime.py
from django.db import models


class MyTime(models.Model):
    title = models.TextField(default='')
    description = models.TextField(default='')
    url = models.TextField(default='')
    started = models.DateTimeField()
    stopped = models.DateTimeField()
    active = models.BooleanField(default=False)
    distance = models.IntegerField(default=0)

    objects = models.Manager()

    def __str__(self):
        return f'[{self.id}] {self.title}'

src/app/views/index.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

src/app/views/mytime.py
from django.shortcuts import render

from app.services.mytime import MyTimeService

mytime_service = MyTimeService()


def mytime(request):
    times = mytime_service.get_all()
    return render(request, 'mytime.html', context={'times': times})

src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoTemplate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>

<body>
    {% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    {% endif %}

    {% block nav %}
    {% endblock nav %}

    {% block content %}
    {% endblock content %}

    {% block script %}
    {% endblock script %}

</body>

</html>

src/app/templates/components/nav.html
{% block nav %}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarMain" class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'app:index' %}" class="navbar-item">Home</a>
            <a href="{% url 'app:mytime' %}" class="navbar-item">My Time</a>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="field is-grouped">
                    <div class="control">
                        {% if user.is_authenticated %}
                        <a href="{% url 'app:logout' %}" class="button is-primary">Logout</a>
                        {% else %}
                        <a href="{% url 'app:register' %}" class="button is-primary">Register</a>
                        <a href="{% url 'app:login' %}" class="button is-light">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>
{% endblock nav %}

{% block script %}
{% endblock script %}

src/app/templates/index.html
{% extends 'base.html' %}

{% block nav %}
{% include 'components/nav.html' %}
{% endblock nav %}

{% block content %}
{% endblock content %}

{% block script %}
{% endblock script %}

src/app/templates/mytime.html
{% extends 'base.html' %}

{% block nav %}
    {% include 'components/nav.html' %}
{% endblock nav %}

{% block content %}
    <div class="container max-width">
        <div class="box">
            <div class="heading">Time Counter</div>
                <div class="title">TITLE</div>
                <div class="level">
                    <div class="level-item">
                        <div class="">
                            <div class="heading">STARTED</div>
                            <div class="title is-5">00:00:00</div>
                        </div>
                    </div>
                    <div class="level-item">
                        <div class="">
                            <div class="heading">STOPPED</div>
                            <div class="title is-5">00:00:00</div>
                        </div>
                    </div>
                    <div class="level-item">
                        <button class="button mx-5">START</button>
                        <button class="button">START</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container my-5 max-width">
        <nav class="box">
            <div class="heading">
                My Time
            </div>
            <div class="panel-block">
                <div class="rows" style="display: flex; flex-direction: column;">
                    <div class="row">
                        <button class="button is-small">Create new task</button>
                    </div>
                    <div class="row">
                        <table class="table is-fullwidth">
                            <thead>
                            <tr>
                                <th><abbr title="Position">Pos</abbr></th>
                                <th><abbr title="Title">Title</abbr></th>
                                <th><abbr title="Description">Description</abbr></th>
                                <th><abbr title="URL">URL</abbr></th>
                                <th><abbr title="Active">Active</abbr></th>
                                <th><abbr title="Started">Started</abbr></th>
                                <th><abbr title="Stopped">Stopped</abbr></th>
                                <th><abbr title="Distance">Distance</abbr></th>
                                <th><abbr title="Actions">Actions</abbr></th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th><abbr title="Position">Pos</abbr></th>
                                <th><abbr title="Title">Title</abbr></th>
                                <th><abbr title="Description">Description</abbr></th>
                                <th><abbr title="URL">URL</abbr></th>
                                <th><abbr title="Active">Active</abbr></th>
                                <th><abbr title="Started">Started</abbr></th>
                                <th><abbr title="Stopped">Stopped</abbr></th>
                                <th><abbr title="Distance">Distance</abbr></th>
                                <th><abbr title="Actions">Actions</abbr></th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for mytime in times %}
                                <tr>
                                    <th>{{ forloop.counter }}</th>
                                    <th>{{ mytime.title }}</th>
                                    <th>{{ mytime.description }}</th>
                                    <th>
                                        {% if mytime.url %}
                                            <a href="{{ mytime.url }}">Go to</a>
                                        {% endif %}
                                    </th>
                                    <th>
                                        {% if mytime.active %}
                                            Active
                                        {% else %}
                                            Inactive
                                        {% endif %}
                                    </th>
                                    <th>{{ mytime.started }}</th>
                                    <th>{{ mytime.stopped }}</th>
                                    <th>{{ mytime.distance }}</th>
                                    <th>
                                        <button class="button is-small">Activate</button>
                                    </th>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </nav>
    </div>
{% endblock content %}

{% block script %}
{% endblock script %}